version: '3.1'

services:
  tests:
    container_name: tests
    build: .
    volumes:
      - ./:/usr/local/src
    depends_on:
      - redis
      - redis-cluster-0
      - swoole
      - workerman

  swoole:
    container_name: swoole
    build: ./tests/Queue/servers/Swoole/.
    command: php /usr/src/code/tests/Queue/servers/Swoole/worker.php
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis

  swoole-redis-cluster:
    container_name: swoole-redis-cluster
    build: ./tests/Queue/servers/SwooleRedisCluster/.
    command: php /usr/src/code/tests/Queue/servers/SwooleRedisCluster/worker.php
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis-cluster-0

  workerman:
    container_name: workerman
    build: ./tests/Queue/servers/Workerman/.
    command: php /usr/src/code/tests/Queue/servers/Workerman/worker.php start
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-cluster-0:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3
      - REDIS_CLUSTER_CREATOR=yes
      - REDIS_CLUSTER_REPLICAS=0
    depends_on:
      - redis-cluster-1
      - redis-cluster-2
      - redis-cluster-3

  redis-cluster-1:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3

  redis-cluster-2:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3

  redis-cluster-3:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3