version: '3.1'

services:
  tests:
    container_name: tests
    build: .
    volumes:
      - ./:/usr/local/src
    depends_on:
      - redis
      - swoole
      - workerman

  swoole:
    container_name: swoole
    build: ./tests/Queue/servers/Swoole/.
    command: php /usr/src/code/tests/Queue/servers/Swoole/worker.php
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis

  workerman:
    container_name: workerman
    build: ./tests/Queue/servers/Workerman/.
    command: php /usr/src/code/tests/Queue/servers/Workerman/worker.php start
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"