services:
  tests:
    container_name: tests
    image: queue-dev-${PHP_VERSION:-8.3}
    build: 
      context: .
      dockerfile: php-${PHP_VERSION:-8.3}.Dockerfile
    volumes:
      - ./:/usr/local/src
    depends_on:
      - redis
      - swoole
      - workerman

  swoole:
    container_name: swoole
    image: queue-dev-${PHP_VERSION:-8.3}
    command: php /usr/src/code/tests/Queue/servers/Swoole/worker.php
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis

  workerman:
    container_name: workerman
    image: queue-dev-${PHP_VERSION:-8.3}
    command: php /usr/src/code/tests/Queue/servers/Workerman/worker.php start
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "9303:6379"

  redis-insight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "9304:5540"